### ISSUE TITLE
Issue with OauthManager.aspx

### ISSUE THREAD

**Issue by imxuf** [IntuitDeveloper/oauth-dotnet#1]
When clicking on the "Connect to QuickBooks" button/link, a new popup window appears, but nothing happens.  It simply shows the same "empty" token values.

**Comment by smathilakath** [comment]
This is fixed.

**Comment by cieMatt** [comment]
I'm having this same issue - downloaded the latest project, followed instructions and entered my app key & secret.

**Comment by Dean-NC** [comment]
I'm on Windows 7 x64 sp1. The app works fine for me in FireFox 39, but does not work in IE 11.  In IE11, I get the same behavior listed by others...a popup window shows that's showing the exact same content as the original startup page.  IE developer tools shows no error in console and that no network request was made.  It seems you probably tested this with Chrome and FireFox, but not IE on Windows 7.

**Comment by Dean-NC** [comment]
Also, the Disconnect button does not work correctly.  On FireFox (and Chrome), clicking it the 1st time does nothing.  Clicking it a 2nd time will take the page to the url where Intuit is asking if you want to share your data with the app.  Basically, you can't disconnect.  The only way is to close the browser, I guess because your bug with disconnect keeps a session variable alive.

**Comment by Dean-NC** [comment]
Thanks Smathilakath, it does work in IE now, but the code is a bit sloppy, here are a couple of cleanup things:
The GetRequestToken() method is dead...meaning it's never called, so you should delete it.  Also, the following line will never get called: if (Request.QueryString["connect"].ToString() == "true")
because you're checking for  QueryString.HasKeys() twice.  The first "if else" is actually the 2nd time you're checking for HasKeys(), so the line: if (Request.QueryString["connect"].ToString() == "true"  will never get called.

**Comment by cieMatt** [comment]
Thanks! Sorry I forgot to mention I was working in IE as well.
