### ISSUE TITLE
Source for SDK

### ISSUE THREAD

**Issue by sinegovsky-ivan** [IntuitDeveloper/oauth-dotnet#2]
Hello!

Is any way to get sources of the https://www.nuget.org/packages/IppDotNetSdkForQuickBooksApiV3/ ?

We need it to small modify of JSON.Net lib.

**Comment by nimisha84** [comment]
Have given you read access to the repo. You can download and use the SDK but we will not accept any commits.

**Comment by sinegovsky-ivan** [comment]
Thank you very much!

You're save a lot of my time :)

**Comment by sinegovsky-ivan** [comment]
Can you tell me please, how i can  build solution?

I reseive about 400 erros, when i try to build \IPPDotNetDevKitCSV3\Code\IppDotNetDevKitCSV3.sln

**Comment by nimisha84** [comment]
Did you restore Nuget Packages and then run it? It will open VS2015 and target framework is 4.0 for all projects.

**Comment by jlmckee14** [comment]
I am having difficulties. I initially loaded in VS2017 but the NuGet packages for Mvc/Razor/WebPages are not working. It indicates the reference can't be found. The updates to the packages don't work because the target framework is 4.5.2. I have tried several older verisons of MVC packages with no luck. Do I have to install VS2015? I am getting the same issues in 2013. 

I apologize if these are stupid questions. I am a database developer and very new to the app development so I am trying to use this download to help me learn (I need the JE functionality, too :) ).

**Comment by nimisha84** [comment]
Hi Jim,

I see your question is related to MVC packages loading issue in VS2017 IDE. I would suggest you to talk Microsoft support or StackOverflow for this issue. If you have any specific issue related to our packages not loading in the VS2017, then I can definitely help.  In any case this sample app does not requires any MVC packages.

Check these-https://www.google.com/search?q=mvc5&oq=mvc5&aqs=chrome..69i57j0j69i61l2j0l2.4535j0j7&sourceid=chrome&ie=UTF-8#q=mvc5+vs2017
